name: uilab
recipe: drupal10
config:
  database: mariadb:10.4
  php: '8.1'
  webroot: web
  xdebug: true
  composer_version: "2.4.2"

env_file:
  - devtools/.env


proxy:
  appserver:
    - uilab.lndo.site
  mailhog:
    - mailhog.uilab.lndo.site
  node:
    - bs.uilab.lndo.site:3000


services:

  #  Container server
  appserver:
    xdebug: true
    config:
      php: devtools/php/conf/xdebug.ini
    type: php:8.1
    overrides:
      environment:
        PHP_IDE_CONFIG: "serverName=appserver"
    build_as_root:
      - rm -f /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && /etc/init.d/apache2 reload
      # Note that you will want to use the script for the major version of node you want to install
      # See: https://github.com/nodesource/distributions/blob/master/README.md#installation-instructions
  #      - curl -sL https://deb.nodesource.com/setup_18.x | bash -
  #      - apt-get install -y nodejs
  #      - chown -R www-data /usr/lib/node_modules
  #      - chown -R www-data /usr/bin
  #      - npm install -g npm
  #      - npm install -g @emulsify/cli

  # Container databases
  database:
    portforward: 3307

  #  Container  Varnish
  #  httpcache:
  #    type: varnish:4.1
  #    backends:
  #      - appserver
  #    backend_port: 80
  #    ssl: false
  #    config:
  #      vcl: devtools/varnish/lando.vcl

  # Container Node pour la compilations des assests css/js
  node:
    type: node:18
    build:
      - echo 'NodeJS container is up and running'
    overrides:
      ports:
        - '3000'
    scanner: false

  # Container Mailhog
  mailhog:
    type: mailhog
    hogfrom:
      - appserver

tooling:
  # FRONTEND
  yarn:
    service: node
  npx:
    service: appserver
  watch:
    service: node
    description: "yarn run watch"
    cmd: "cd $LANDO_MOUNT/web/themes/custom/uilab/assets && yarn watch"
  build-dev:
    service: node
    description: "yarn dev"
    cmd: "cd $LANDO_MOUNT/web/themes/custom/uilab/assets && yarn dev"
  build-prod:
    service: node
    description: "yarn prod"
    cmd: "cd $LANDO_MOUNT/web/themes/custom/uilab/assets && yarn prod"

  # TEST
  phpcs:
    service: appserver
    cmd: "phpcs --standard=Drupal,DrupalPractice"
    description: Run phpcs Drupal Coding Standards against a given file or directory.
  phpcbf:
    service: appserver
    cmd: "phpcbf --standard=Drupal"
    description: Automatically fix Drupal coding standards suggestions.


  #  APACHE VERSION
  xdebug-on:
    service: appserver
    description: Enable xdebug for nginx.
    cmd: docker-php-ext-enable xdebug && pkill -o -USR2 php-fpm
    user: root

  xdebug-off:
    service: appserver
    description: Disable xdebug for nginx.
    cmd: rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && pkill -o -USR2 php-fpm
    user: root

